language: node_js
node_js:
  - "11"
git:
  depth: false
cache:
  directories:
    — node_modules
install:
  - yarn
before_script:
  - yarn run mock &
script:
  - yarn run test
  - yarn run lint
after_script:
  - yarn run mock:stop
deploy:
  provider: script
  script: 
    - yarn run build
    - yarn publish --new-version ${TRAVIS_TAG} --no-git-tag-version
  skip_cleanup: true
  on:
    tags: true