language: node_js
node_js:
  - "11"
git:
  depth: false
cache:
  directories:
    — node_modules
install:
  - yarn
before_script:
  - yarn run mock
script:
  - yarn run test
after_script:
  - yarn run mock:stop
